// Code generated by goagen v1.1.0, command line:
// $ goa_gen
//
// API "CopperMantis": monitoring Resource Client
//
// The content of this file is auto-generated, DO NOT MODIFY

package client

import (
	"fmt"
	"golang.org/x/net/context"
	"net/http"
	"net/url"
)

// PingMonitoringPath computes a request path to the ping action of monitoring.
func PingMonitoringPath() string {

	return fmt.Sprintf("/cms/v1/_ping")
}

// Perform health check.
func (c *Client) PingMonitoring(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewPingMonitoringRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewPingMonitoringRequest create the request corresponding to the ping action endpoint of the monitoring resource.
func (c *Client) NewPingMonitoringRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
