// Code generated by goagen v1.1.0, command line:
// $ goa_gen
//
// API "CopperMantis": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// ContestHref returns the resource href.
func ContestHref(contestID interface{}) string {
	paramcontestID := strings.TrimLeftFunc(fmt.Sprintf("%v", contestID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/cms/v1/contest/%v", paramcontestID)
}

// DocumentHref returns the resource href.
func DocumentHref(documentID interface{}) string {
	paramdocumentID := strings.TrimLeftFunc(fmt.Sprintf("%v", documentID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/cms/v1/document/%v", paramdocumentID)
}

// ProfileHref returns the resource href.
func ProfileHref(profileID interface{}) string {
	paramprofileID := strings.TrimLeftFunc(fmt.Sprintf("%v", profileID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/cms/v1/profile/%v", paramprofileID)
}
